---
title: "Practical 5: Pivots + great tables"
from: markdown+emoji
execute:
  include: false
  echo: false
---

The objective of the tutorial is to give student a chance to practice the data wrangling and joins applying the skills learned through the video lessons on a new dataset.

## Preparation

:::{.callout-note}

Before you begin your peer-programming session, please, start the new Jupyter notebook environment in your terminal from your project directory using the command you learned in Module 1 of the course.

```
uv run jupyter lab
```

Create a new notebook and add a text cell atop your document for this practical session. Add a header `# Pivots and great tables`. Then add a code cell and place the following code there.

```{python}
#| echo: true
#| include: true
import polars as pl
import polars.selectors as cs
from plotnine import *
from great_tables import GT
```

Then import the datasets for this practical. Add another code cell below (using the key 'B') and paste the following code. This will import .

```{python}
# | echo: true
# | include: true

ut = pl.read_csv("https://bit.ly/data24utrecht", try_parse_dates=True)

cia_area = pl.read_csv("data/factbook_area_2024.csv")
cia_commtran = pl.read_csv("data/factbook_comm_transport_2024.csv")
cia_ecosec = pl.read_csv("data/factbook_economy_security_2024.csv")
cia_enenv = pl.read_csv("data/factbook_energy_environment_2024.csv")
cia_pplsoc = pl.read_csv("data/factbook_people_society_2024.csv")
iso_df = pl.read_csv("https://bit.ly/data24-countrycodes")
```

:::

# CIA

Answer the following challenges using [CIA](CIA.qmd) datasets.

## Challenge 1

:::{.challenge}
Calculate share of GDP from sources other than industry, services and agriculture for all countries in Africa. Present results in great table sorted from largest to smallest. Do you find anything strange about the data?
:::

```{python}
(
    cia_ecosec
    .filter(pl.col('region')=='Africa')
    .select('name', cs.starts_with('gdp_composition'))
    .unpivot(on=cs.starts_with('gdp_composition'), index='name')
    .group_by('name')
    .agg(other_sources=100-pl.col('value').sum())
    .sort('other_sources', descending=True)
)
```

## Challenge 2

:::{.challenge}
| Select the summary quantiles produced by the `.describe()` method for all variables containing the term "rate" in the People and Society dataset and plot the point estimates using a set of points for every variable. Color the points by the quantile level.
| :bulb: Minimum value is corresponding to the 0th quantile and maximum is coinciding with the 100th quantile.
:::

```{python}
(
    cia_pplsoc
    .describe()
    .select("statistic", cs.contains("rate"))
    .tail(5)
    .unpivot(index="statistic")
    .with_columns(statistic=pl.when(pl.col("statistic")=="min")
                        .then(pl.lit("0%"))
                        .when(pl.col("statistic")=="max")
                        .then(pl.lit("100%"))
                        .otherwise(pl.col("statistic")))
    .pipe(ggplot, aes(x="variable", y="value", color="statistic"))
    + geom_point(size=3)
    + coord_flip()
)
```

## Challenge 3

:::{.challenge}
| Reproduce the plot.
| :bulb: The plot is built using `geom_segment()`
:::

```{python}
(
    cia_pplsoc.describe()
    .select("statistic", cs.contains("rate"))
    .tail(5)
    .unpivot(index="statistic")
    .with_columns(
        statistic=pl.when(pl.col("statistic") == "min")
        .then(pl.lit("q_0%"))
        .when(pl.col("statistic") == "max")
        .then(pl.lit("q_100%"))
        .otherwise(pl.lit("q_") + pl.col("statistic"))
    )
    .pivot(on="statistic", values="value")
    .pipe(ggplot)
    + geom_point(aes(y="q_50%", x="variable"), size=3)
    + geom_segment(aes(x="variable", xend="variable", y="q_25%", yend="q_75%"), size=2)
    + geom_segment(aes(x="variable", xend="variable", y="q_0%", yend="q_100%"), size=0.5)
    + coord_flip()
    + labs(x="", y="Rate", title="People and Society metics",
            subtitle="Min, max, median and interquartile range",
            caption="Source: CIA Factbook 2024")
)
```

## Challenge 4

:::{.challenge}
| Compare the values of variables containing the term "rate" in the People and Society dataset for Sweden and Denmark. Present results as a great table with two columns - one for each country.
| :bulb: See if you can make the table look more clean by replacing some symbols with `.str.replace_all()`
:::

```{python}
(
    cia_pplsoc
    .select('name', cs.ends_with('_rate'))
    .filter(pl.col('name').is_in(['Denmark', 'Sweden']))
    .unpivot(on=cs.ends_with('rate'), index='name', variable_name="rate", value_name="value")
    .pivot(on='name', index='rate', values='value')
    .with_columns(rate=pl.col('rate').str.replace_all('_', ' ').str.to_titlecase())
    .pipe(GT)
    .opt_stylize(1)
)
```

## Challenge 5

:::{.challenge}
| Create a great table comparing the proportion of missing values across all numeric columns in the joined CIA Factbook datasets by region.
:::

```{python}
(
    cia_area
    .join(cia_commtran, on=["name", "slug", "region"], how="full", coalesce=True)
    .join(cia_ecosec, on=["name", "slug", "region"], how="full", coalesce=True)
    .join(cia_enenv, on=["name", "slug", "region"], how="full", coalesce=True)
    .join(cia_pplsoc, on=["name", "slug", "region"], how="full", coalesce=True)
    .group_by('region')
    .agg(cs.all().is_null().mean())
    .drop("name", "slug")
    .unpivot(index='region')
    .pivot(on="region", index="variable")
    .pipe(GT)
    .fmt_percent(columns=cs.numeric(), decimals=1)
    .opt_stylize(1)
)
```
